### PR TITLE
chore(readme): fix typos

### PR DESCRIPTION
**Pull request by rubyconvict**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fa1a49f025a44616fbcc21cf31feb95e4e87806e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mattfreer/active_model_form_objects

---
This message was auto-generated by https://gitcop.com

**Comment by mattfreer-mdsol** [comment]
@rubyconvict Thanks for PR, If you could amend your commit message to the following I'm more than happy to merge:

```bash
chore(readme): fix typos

fixed typos in README.
```

**Comment by rubyconvict** [comment]
done

**Comment by mattfreer** [comment]
@rubyconvict Looks like there is an issue with the CI server config. I'll add a fix and get the builds passing again.

**Comment by mattfreer** [comment]
@rubyconvict I have fixed the issue with the CI server config. Could you rebase the latest master branch into your branch and force push to GH. Thanks.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 443b4fbcfaad44e2c7e5d63f609fc0759e1ef47a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mattfreer/active_model_form_objects

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
